name: Build C++ Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile C++ code
      run: g++ -o query_engine main/main.cpp

    - name: Run executable
      run: ./query_engine
