name: Build C++ Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Compile all .cpp files
      run: |
        FILES=$(find . -type f -name "*.cpp")
        g++ -std=c++17 -Wall -Wextra $FILES -o query_engine

    - name: Run executable
      run: ./query_engine
